FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04

RUN apt update && apt install -y \
        python3.8 \
        python3-pip \
        curl \
        wget \
        git \
        git-lfs \
        dcm2niix && \
        apt-key del 7fa2af80 && \
        curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && \
        dpkg -i cuda-keyring_1.0-1_all.deb && \
    apt clean

RUN rm /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python

RUN python3 -m pip install --upgrade pip
COPY requirements.txt /env/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt

COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]
